import { google } from '@ai-sdk/google';
import {
  convertToModelMessages,
  streamText,
  type UIMessage,
} from 'ai';

export const POST = async (req: Request): Promise<Response> => {
  const body: { messages: UIMessage[] } = await req.json();
  const { messages } = body;

  // In general, we persist the message to db after it has
  // finished streaming. There are other options as well.
  const result = streamText({
    model: google('gemini-2.0-flash'),
    messages: convertToModelMessages(messages),
    onFinish: ({ response }) => {
      // 'response.messages' type is ResponseMessage[] which is an array
      // of ToolModelMessage and AssistantModelMessage, which are the
      // model messages that were generated during the stream. Their
      // type is subset of ModelMessage. This is useful if you don't
      // need UIMessages(for simpler applications without UI).
      console.log('streamText.onFinish');
      console.log('  response.messages');
      console.dir(response.messages, { depth: null });
    },
  });

  return result.toUIMessageStreamResponse({
    // This is the message received from UI in the request.
    // It has entire history of messages & is optional parameter.
    // If we don't pass this, then the message in onFinish
    // callback will only have the messages generated during
    // the stream.
    originalMessages: messages,
    onFinish: ({ messages, responseMessage }) => {
      // 'messages' is the full message history, including the original messages
      // you pass in to originalMessages.
      console.log('toUIMessageStreamResponse.onFinish');
      console.log('  messages');
      console.dir(messages, { depth: null });

      // 'responseMessage' is a single & last message generated by
      // result.toUIMessageStreamResponse().
      console.log('toUIMessageStreamResponse.onFinish');
      console.log('  responseMessage');
      console.dir(responseMessage, { depth: null });
    },
  });
};

/* Output from code above when a request is made from the client:

streamText.onFinish
  response.messages
[
  {
    role: 'assistant',
    content: [
      {
        type: 'text',
        text: 'There once was a fish named Grant,\n' +
          'Whose scales shone, a shimmering slant\n' +
          'Of emerald green,\n' +
          'A beautiful sheen,\n' +
          'The envy of every small plant.\n' +
          '\n' +
          'He lived in a coral so bright,\n' +
          'And swam with all of his might,\n' +
          'A flick of the tail,\n' +
          "He'd leave in his trail,\n" +
          'A bubbly and shimmering light.\n' +
          '\n' +
          "Grant wasn't just handsome and strong,\n" +
          'He knew every kelp forest song,\n' +
          'From the clicking of shrimp,\n' +
          'To the bubbles that imp,\n' +
          'His cleverness lasted all day long.\n' +
          '\n' +
          'He courted a lovely Miss Merle,\n' +
          'Whose fins had a pearlescent swirl,\n' +
          'With gifts of sea-glass,\n' +
          'He aimed to surpass,\n' +
          'The other fish vying to unfurl.\n' +
          '\n' +
          'So Grant, with his charm and his grace,\n' +
          'Found love in this watery space,\n' +
          'He built her a nest,\n' +
          'And put her to the test,\n' +
          'A fish tale with a happy embrace.\n',
        providerOptions: undefined
      }
    ]
  }
]
toUIMessageStreamResponse.onFinish
  messages
[
  {
    parts: [
      {
        type: 'text',
        text: 'Write me a poem about a fish called Grant.'
      }
    ],
    id: 'Ts6gkJNzFS3kcxRO',
    role: 'user'
  },
  {
    id: '',
    metadata: undefined,
    role: 'assistant',
    parts: [
      { type: 'step-start' },
      {
        type: 'text',
        text: 'There once was a fish named Grant,\n' +
          'Whose scales shone, a shimmering slant\n' +
          'Of emerald green,\n' +
          'A beautiful sheen,\n' +
          'The envy of every small plant.\n' +
          '\n' +
          'He lived in a coral so bright,\n' +
          'And swam with all of his might,\n' +
          'A flick of the tail,\n' +
          "He'd leave in his trail,\n" +
          'A bubbly and shimmering light.\n' +
          '\n' +
          "Grant wasn't just handsome and strong,\n" +
          'He knew every kelp forest song,\n' +
          'From the clicking of shrimp,\n' +
          'To the bubbles that imp,\n' +
          'His cleverness lasted all day long.\n' +
          '\n' +
          'He courted a lovely Miss Merle,\n' +
          'Whose fins had a pearlescent swirl,\n' +
          'With gifts of sea-glass,\n' +
          'He aimed to surpass,\n' +
          'The other fish vying to unfurl.\n' +
          '\n' +
          'So Grant, with his charm and his grace,\n' +
          'Found love in this watery space,\n' +
          'He built her a nest,\n' +
          'And put her to the test,\n' +
          'A fish tale with a happy embrace.\n',
        providerMetadata: undefined,
        state: 'done'
      }
    ]
  }
]
toUIMessageStreamResponse.onFinish
  responseMessage
{
  id: '',
  metadata: undefined,
  role: 'assistant',
  parts: [
    { type: 'step-start' },
    {
      type: 'text',
      text: 'There once was a fish named Grant,\n' +
        'Whose scales shone, a shimmering slant\n' +
        'Of emerald green,\n' +
        'A beautiful sheen,\n' +
        'The envy of every small plant.\n' +
        '\n' +
        'He lived in a coral so bright,\n' +
        'And swam with all of his might,\n' +
        'A flick of the tail,\n' +
        "He'd leave in his trail,\n" +
        'A bubbly and shimmering light.\n' +
        '\n' +
        "Grant wasn't just handsome and strong,\n" +
        'He knew every kelp forest song,\n' +
        'From the clicking of shrimp,\n' +
        'To the bubbles that imp,\n' +
        'His cleverness lasted all day long.\n' +
        '\n' +
        'He courted a lovely Miss Merle,\n' +
        'Whose fins had a pearlescent swirl,\n' +
        'With gifts of sea-glass,\n' +
        'He aimed to surpass,\n' +
        'The other fish vying to unfurl.\n' +
        '\n' +
        'So Grant, with his charm and his grace,\n' +
        'Found love in this watery space,\n' +
        'He built her a nest,\n' +
        'And put her to the test,\n' +
        'A fish tale with a happy embrace.\n',
      providerMetadata: undefined,
      state: 'done'
    }
  ]
}
streamText.onFinish
  response.messages
[
  {
    role: 'assistant',
    content: [
      {
        type: 'text',
        text: 'There once was a dog named Rocky,\n' +
          'Whose fur was a shade quite stocky,\n' +
          'A mix of brown, black,\n' +
          'Upon his back,\n' +
          "He'd romp through the fields feeling lucky.\n" +
          '\n' +
          'He loved to chase squirrels up a tree,\n' +
          'And bark with enthusiastic glee,\n' +
          'A happy loud sound,\n' +
          "As he spun 'round and 'round,\n" +
          'A whirlwind of canine energy.\n' +
          '\n' +
          'His tail was a wagging machine,\n' +
          'The happiest sight ever seen,\n' +
          "He'd greet you with leaps,\n" +
          'While sniffing your keeps,\n' +
          'And cover you in slobbery sheen.\n' +
          '\n' +
          "He'd beg for a scratch behind ears,\n" +
          'And conquer all canine-held fears,\n' +
          'From thunderstorms loud,\n' +
          'To the menacing crowd,\n' +
          'Rocky would dry away all your tears.\n' +
          '\n' +
          'So give a good pat to brave Rocky,\n' +
          'A loyal and loving old socky,\n' +
          "He's man's best of friends,\n" +
          'Whose love never ends,\n' +
          'A champion, truly, quite shocky!\n',
        providerOptions: undefined
      }
    ]
  }
]
toUIMessageStreamResponse.onFinish
  messages
[
  {
    parts: [
      {
        type: 'text',
        text: 'Write me a poem about a fish called Grant.'
      }
    ],
    id: 'Ts6gkJNzFS3kcxRO',
    role: 'user'
  },
  {
    id: 'nTdNjkHjVaLeqE11',
    role: 'assistant',
    parts: [
      { type: 'step-start' },
      {
        type: 'text',
        text: 'There once was a fish named Grant,\n' +
          'Whose scales shone, a shimmering slant\n' +
          'Of emerald green,\n' +
          'A beautiful sheen,\n' +
          'The envy of every small plant.\n' +
          '\n' +
          'He lived in a coral so bright,\n' +
          'And swam with all of his might,\n' +
          'A flick of the tail,\n' +
          "He'd leave in his trail,\n" +
          'A bubbly and shimmering light.\n' +
          '\n' +
          "Grant wasn't just handsome and strong,\n" +
          'He knew every kelp forest song,\n' +
          'From the clicking of shrimp,\n' +
          'To the bubbles that imp,\n' +
          'His cleverness lasted all day long.\n' +
          '\n' +
          'He courted a lovely Miss Merle,\n' +
          'Whose fins had a pearlescent swirl,\n' +
          'With gifts of sea-glass,\n' +
          'He aimed to surpass,\n' +
          'The other fish vying to unfurl.\n' +
          '\n' +
          'So Grant, with his charm and his grace,\n' +
          'Found love in this watery space,\n' +
          'He built her a nest,\n' +
          'And put her to the test,\n' +
          'A fish tale with a happy embrace.\n',
        state: 'done'
      }
    ]
  },
  {
    parts: [
      { type: 'text', text: 'write a poem about a dog called rocky.' }
    ],
    id: 'lTf19Es7lKd2yzBS',
    role: 'user'
  },
  {
    id: '',
    metadata: undefined,
    role: 'assistant',
    parts: [
      { type: 'step-start' },
      {
        type: 'text',
        text: 'There once was a dog named Rocky,\n' +
          'Whose fur was a shade quite stocky,\n' +
          'A mix of brown, black,\n' +
          'Upon his back,\n' +
          "He'd romp through the fields feeling lucky.\n" +
          '\n' +
          'He loved to chase squirrels up a tree,\n' +
          'And bark with enthusiastic glee,\n' +
          'A happy loud sound,\n' +
          "As he spun 'round and 'round,\n" +
          'A whirlwind of canine energy.\n' +
          '\n' +
          'His tail was a wagging machine,\n' +
          'The happiest sight ever seen,\n' +
          "He'd greet you with leaps,\n" +
          'While sniffing your keeps,\n' +
          'And cover you in slobbery sheen.\n' +
          '\n' +
          "He'd beg for a scratch behind ears,\n" +
          'And conquer all canine-held fears,\n' +
          'From thunderstorms loud,\n' +
          'To the menacing crowd,\n' +
          'Rocky would dry away all your tears.\n' +
          '\n' +
          'So give a good pat to brave Rocky,\n' +
          'A loyal and loving old socky,\n' +
          "He's man's best of friends,\n" +
          'Whose love never ends,\n' +
          'A champion, truly, quite shocky!\n',
        providerMetadata: undefined,
        state: 'done'
      }
    ]
  }
]
toUIMessageStreamResponse.onFinish
  responseMessage
{
  id: '',
  metadata: undefined,
  role: 'assistant',
  parts: [
    { type: 'step-start' },
    {
      type: 'text',
      text: 'There once was a dog named Rocky,\n' +
        'Whose fur was a shade quite stocky,\n' +
        'A mix of brown, black,\n' +
        'Upon his back,\n' +
        "He'd romp through the fields feeling lucky.\n" +
        '\n' +
        'He loved to chase squirrels up a tree,\n' +
        'And bark with enthusiastic glee,\n' +
        'A happy loud sound,\n' +
        "As he spun 'round and 'round,\n" +
        'A whirlwind of canine energy.\n' +
        '\n' +
        'His tail was a wagging machine,\n' +
        'The happiest sight ever seen,\n' +
        "He'd greet you with leaps,\n" +
        'While sniffing your keeps,\n' +
        'And cover you in slobbery sheen.\n' +
        '\n' +
        "He'd beg for a scratch behind ears,\n" +
        'And conquer all canine-held fears,\n' +
        'From thunderstorms loud,\n' +
        'To the menacing crowd,\n' +
        'Rocky would dry away all your tears.\n' +
        '\n' +
        'So give a good pat to brave Rocky,\n' +
        'A loyal and loving old socky,\n' +
        "He's man's best of friends,\n" +
        'Whose love never ends,\n' +
        'A champion, truly, quite shocky!\n',
      providerMetadata: undefined,
      state: 'done'
    }
  ]
}

*/
